server:
  port: 8000

spring:
  application:
    name: server-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///${MINIUBER_PATH_BAS}/server-properties/